<?php
/**
 * @var $this Granify_Sales_Block_Adminhtml_System_Config_Fieldset_Notice
 */
?>
<style type="text/css">
    .granify_settings_label {font: 14px bold;}
</style>
<table class="" id="" cellspacing="0">
    <col width="100%" />
    <tbody>
        <tr>
            <td class="granify_settings_label"><?php echo $this->escapeHtml($this->getFieldsetLabel()) ?></td>
        </tr>
    </tbody>
</table>
